### ISSUE TITLE
Failing PEP8

### ISSUE THREAD

**Issue by Ryuno-Ki** [vrypan/webmention-tools#13]
Hi,

I am currently trying out your package and would like to contribute by first fixing the PEP8 errors (which blocks this package from using).

```python
>>> from webmentiontools.urlinfo import UrlInfo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "$HOME/$VIRTUALENVROOT/lib/python3.5/site-packages/webmentiontools/urlinfo.py", line 24
    r.encoding = r.apparent_encoding
                                    ^
TabError: inconsistent use of tabs and spaces in indentation
```

Would you be willing to accept a PR?

**Comment by Ryuno-Ki** [comment]
Following things has to be changed in the business logic in [urlinfo.py](https://github.com/vrypan/webmention-tools/blob/2b0a4069ecebbdb46bbf271f5b68ee48031bf242/webmentiontools/urlinfo.py)
* `from urlparse import urljoin` => `from urllib.parse import urljoin`
* `if self.data.has_key('image'):` => `if 'image' in self.data:`
* Instantiation of `UrlInfo` triggers a warning in BeautifulSoup regarding a missing specification of HTML parser.
* `print`s needs `()`

With those changes I can confirm that the [Python code snippet to get UrlInfo](https://github.com/vrypan/webmention-tools/#usage) runs.

**Comment by vrypan** [comment]
Hi. Of course I will accept the PR! Thanks in advance.

**Comment by Ryuno-Ki** [comment]
I'd welcome if you could publish a new version after merging #15.

* GitHub [Creating Releases](https://help.github.com/articles/creating-releases/)
* PyPI [Packaging and Distributing Projects](https://packaging.python.org/tutorials/distributing-packages/#packaging-your-project)
* Python Warehouse [is looking for package maintainers](https://pyfound.blogspot.de/2018/02/python-package-maintainers-help-test.html) to try out the next-gen PyPI

Thanks in advance.
